### ISSUE TITLE
publish wheels for linux

### ISSUE THREAD

**Issue by DetachHead** [ohaswin/pyscan#18]
**Is your feature request related to a problem? Please describe.**
currently there are only wheels for windows and macos, so it fails to build when i attempt to run it in my CI which uses ubuntu

**Describe the solution you'd like**
publish wheels for linux

**Describe alternatives you've considered**
figuring out why it fails to build. i would rather not have to figure out how to install the rust compiler in my CI, as our dockerfile is already very bloated and debugging build issues in CI is extremely painful

**Additional context**

**Comment by KotlinIsland** [comment]
i figured it out!

```console
curl https://sh.rustup.rs -sSf | sh
```

**Comment by DetachHead** [comment]
doesnt work

**Comment by ohaswin** [comment]
Hey, for the latest stable, i do have wheels published in the [releases](https://github.com/aswinnnn/pyscan/releases) page. you'll find it with the `manylinux` suffix. Your CI should be able to do this:

```bash
pip install https://github.com/aswinnnn/pyscan/releases/download/v0.1.4/pyscan_rs-0.1.4-py3-none-manylinux_2_34_x86_64.whl
```

I just tested it on my Debian and it installs fine. Let me know if it doesn't work.

**Comment by KotlinIsland** [comment]
I use pypi in my ci, would it be possible to upload the wheels to the pypi release?

**Comment by ohaswin** [comment]
There's no way to edit pypi releases to add wheels unfortunately, My PyPI CI fails horribly at manylinux builds, which is why I manually built it and uploaded it to releases instead. 

However, I have been working on and off on a new version of pyscan (#17), I could upload a beta version with the manylinux wheels included. Would you be into that? There might be unforeseen bugs which you might have to report, if you're cool with it.

**Comment by KotlinIsland** [comment]
> There's no way to edit pypi releases to add wheels unfortunately

I've done it many times

**Comment by ohaswin** [comment]
I can't seem to find such an option, I'll look more into it.

**Comment by KotlinIsland** [comment]
so what i've done is run `twine upload` with the new wheels. it won't let you override an existing release file/wheel, but it will let you add new ones

**Comment by ohaswin** [comment]
thank you! the [wheel](https://files.pythonhosted.org/packages/27/3d/25ed135808342bb0bcbbf76727ecff3b6ee966b453940fb530d24475e816/pyscan_rs-0.1.6-py3-none-manylinux_2_34_x86_64.whl) is included now. Let me know if you have any issues.
