### ISSUE TITLE
Exit with zero in case of vulnerability found

### ISSUE THREAD

**Issue by anotherbridge** [ohaswin/pyscan#2]
**Describe the bug**
When a vulnerability was found the exit code of the program is zero. Thus it makes it hard to integrate the tool into an automation that should raise an alert in case a vulnerability was found. This is the case when running pyscan either for a specific package or within a repository.

**To Reproduce**
1. Run `pyscan package -n requests -v 2.30.0`
2. Run `echo $?`
3. Observe that `0` is returned

**Expected behavior**
It is expected that a non-zero exit code is returned in case a vulnerability is found.

**Desktop (please complete the following information):**
 - OS: macOS Ventura ARM architecture, Debian 11.7 x86 architecture

**Comment by ohaswin** [comment]
Yes, this is a known case and will be integrated as default way of exiting in the new version as mentioned in the future notes in [CHANGELOG.md](https://github.com/aswinnnn/pyscan/tree/master/CHANGELOG.md). I will be closing this issue as its already taken care of and will be released within the next version.

**Comment by anotherbridge** [comment]
@aswinnnn Is this behavior already released, since I can still not get an exit code of 1 when a vulnerability was detected in one of the packages. The non-zero exit code is only producable when the tool itself encounters an error, e.g. such as described in #16.

**Comment by ohaswin** [comment]
It was released, but I moved the scanner functions around in the latest version and looks like I forgot about the exit codes. Fixing it ASAP.

**Comment by anotherbridge** [comment]
Thanks a lot!
